// 章节数据。第4章扩展 = 在此追加一条记录，引擎零改动。
// objectives: 该章主线任务列表；endQuest 完成后自动 finishChapter。

export const CHAPTERS = [
  { id: 'ch1', index: 1, title: '渔村夜袭', subtitle: '穿越者与覆灭的故乡',
    introFlag: 'FLAG_CH1_START',
    intro: '潮声，从很久以前就融进了你的梦里。\n\n你本不属于这个世界。一场意外将你卷入此地，落在东海边这座名叫海风的小渔村，一住就是多年。乡亲们早已忘了你是外乡人，你也几乎忘了故土的模样。\n\n然而那一夜，海面泛起了诡异的光。\n\n魔物从浪里涌了上来。篝火熄灭，木屋坍塌，平日里亲切的面孔，在夜色里一个个倒了下去。\n\n你握住了废墟里那把生锈的短剑。\n\n……是时候，讨回这笔血债了。',
    startingMap: 'REGION_FISHING',
    objectives: ['Q1_CH1_VILLAGE_DESTROYED', 'Q2_CH1_CLEAR_CAVE', 'Q3_CH1_HUNT', 'Q4_CH1_BOSS'],
    endQuest: 'Q4_CH1_BOSS',
    gate: { flag: 'FLAG_CH1_CLEAR' },
    next: 'ch2',
    interlude: '你提着魔潮头目的头颅走回渔村时，天已微亮。\n\n铁臂将军审视着你，目光从怀疑变为赞许。他抛给你一枚盖着王印的徵召令。\n\n「从今日起，你便是王军的一员了。」\n\n你望着东方泛白的天际线。渔村的炊烟重新升起，可你知道，这片大陆的黑暗，才刚刚揭开一角。\n\n—— 第一章 · 完',
  },
  { id: 'ch2', index: 2, title: '讨伐魔王之路', subtitle: '军团、背叛，与深渊',
    introFlag: 'FLAG_CH2_START',
    intro: '你加入了讨伐魔王的王军。\n\n军营的生活比想象中更喧闹、更肮脏。你跟着同袍们剿魔、护送、夺回失陷的据点，刀口舔血，却也渐渐明白——军队的荣耀背后，是腐烂的账本、被克扣的军饷，和一个个被悄悄抹去的名字。\n\n直到那夜，你亲眼看见战友倒下，看见所谓的统帅露出獠牙。\n\n你卸下了盔甲，走出军营。\n\n从此，大陆上多了一个独行的猎人。',
    startingMap: 'REGION_ARMY',
    objectives: ['Q2_CH2_MISSION', 'Q2_CH2_RATIONS', 'Q2_CH2_BETRAYAL', 'Q2_CH2_TRAINING', 'Q2_CH2_FINAL'],
    endQuest: 'Q2_CH2_FINAL',
    gate: { flag: 'FLAG_CH2_CLEAR' },
    next: 'ch3',
    interlude: '魔王的深渊之力灌入你的躯体，灼烧着每一寸血肉。\n\n你跪倒在王座之前，听见体内有无数声音在嘶吼——臣服吧，成为新的深渊。\n\n但你没有。\n\n你从一片混沌中抬起头，那双眼睛里，仍然是人类的光。\n\n「我……还是我。」你抓住魔王的王冠，把它掷进了火里。\n\n「但这座大陆，已经不值得我守护了。」\n\n你转身，身后是沉默列队的魔物。它们认你为王。\n\n你带着它们，走向大陆尽头的天裂隘口。那里有一片无人的新大陆，在等待它的主人。\n\n—— 第二章 · 完',
  },
  { id: 'ch3', index: 3, title: '百年之约', subtitle: '魔王的调停',
    introFlag: 'FLAG_CH3_START',
    intro: '百年光阴，对凡人来说是一生，对魔王来说，只是一瞬。\n\n你在无人大陆上建起了魔都，教魔物们耕种、冶炼、彼此善待。人间的纷争仿佛已是很久远的事。\n\n直到那一天，一名浑身浴血的使节跪倒在幽都的城门下。\n\n「人族与精灵……开战了。」\n\n「人类……快亡了。」\n\n你望向海的对岸。那里有你的故土，有你尘封的记忆，也有这百年来你一直逃避的东西。\n\n你站起身。百万魔物大军，无声地列阵待命。\n\n「备船。我们回去，调停这场战争。」',
    startingMap: 'REGION_ISLAND',
    objectives: ['Q3_CH3_DISTRESS', 'Q3_CH3_FIND_CAUSE', 'Q3_CH3_MEDIATE', 'Q3_CH3_FINAL'],
    endQuest: 'Q3_CH3_FINAL',
    gate: { flag: 'FLAG_CH3_CLEAR' },
    next: null,
    interlude: '战争之主的残骸在圣树下渐渐冷却。\n\n人类国王、精灵长老，与你一同站在这片刚刚还浸满鲜血的土地上。三族沉默了许久。\n\n最终，是人类国王先开了口。\n\n「战争……结束了。」\n\n你点了点头，将那份三族和平条约递了出去。\n\n海风吹过圣林，拂过你王冠下的白发。远处，魔物与人类、精灵的旗帜，第一次并肩而立。\n\n你忽然想起许多年前，渔村里那个提剑的少年。\n\n你笑了。\n\n—— 第三章 · 完\n\n（旅程仍在继续。魔物的故事，远未结束……）',
  },
];
